// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => _firebaseOptions(
        apiKey: _required('FIREBASE_WEB_API_KEY'),
        appId: _required('FIREBASE_WEB_APP_ID'),
        messagingSenderId: _required('FIREBASE_MESSAGING_SENDER_ID'),
        projectId: _required('FIREBASE_PROJECT_ID'),
        authDomain: _required('FIREBASE_AUTH_DOMAIN'),
        storageBucket: _required('FIREBASE_STORAGE_BUCKET'),
      );

  static FirebaseOptions get android => _firebaseOptions(
        apiKey: _required('FIREBASE_ANDROID_API_KEY'),
        appId: _required('FIREBASE_ANDROID_APP_ID'),
        messagingSenderId: _required('FIREBASE_MESSAGING_SENDER_ID'),
        projectId: _required('FIREBASE_PROJECT_ID'),
        storageBucket: _required('FIREBASE_STORAGE_BUCKET'),
      );

  static FirebaseOptions get ios => _firebaseOptions(
        apiKey: _required('FIREBASE_IOS_API_KEY'),
        appId: _required('FIREBASE_IOS_APP_ID'),
        messagingSenderId: _required('FIREBASE_MESSAGING_SENDER_ID'),
        projectId: _required('FIREBASE_PROJECT_ID'),
        storageBucket: _required('FIREBASE_STORAGE_BUCKET'),
        iosBundleId: _required('FIREBASE_IOS_BUNDLE_ID'),
      );

  static FirebaseOptions get macos => _firebaseOptions(
        apiKey: _required('FIREBASE_MACOS_API_KEY'),
        appId: _required('FIREBASE_MACOS_APP_ID'),
        messagingSenderId: _required('FIREBASE_MESSAGING_SENDER_ID'),
        projectId: _required('FIREBASE_PROJECT_ID'),
        storageBucket: _required('FIREBASE_STORAGE_BUCKET'),
        iosBundleId: _required('FIREBASE_MACOS_BUNDLE_ID'),
      );

  static FirebaseOptions _firebaseOptions({
    required String apiKey,
    required String appId,
    required String messagingSenderId,
    required String projectId,
    String? authDomain,
    String? storageBucket,
    String? iosBundleId,
  }) {
    return FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      authDomain: authDomain,
      storageBucket: storageBucket,
      iosBundleId: iosBundleId,
    );
  }

  static String _required(String key) {
    final value = dotenv.env[key];
    if (value == null || value.isEmpty) {
      throw StateError('Missing required env var: $key');
    }
    return value;
  }
}
