// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmRLOqycZl5Ms2YX88iLJ3IhnldwrKxWM',
    appId: '1:596238938882:web:YOUR_WEB_APP_ID', // TODO: Add web app if needed
    messagingSenderId: '596238938882',
    projectId: 'storehsk-94540',
    authDomain: 'storehsk-94540.firebaseapp.com',
    storageBucket: 'storehsk-94540.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmRLOqycZl5Ms2YX88iLJ3IhnldwrKxWM',
    appId: '1:596238938882:android:7eee47b4d654468e9b081b',
    messagingSenderId: '596238938882',
    projectId: 'storehsk-94540',
    storageBucket: 'storehsk-94540.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmRLOqycZl5Ms2YX88iLJ3IhnldwrKxWM',
    appId: '1:596238938882:ios:YOUR_IOS_APP_ID', // TODO: Add iOS app if needed
    messagingSenderId: '596238938882',
    projectId: 'storehsk-94540',
    storageBucket: 'storehsk-94540.firebasestorage.app',
    iosBundleId: 'com.example.storehsk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmRLOqycZl5Ms2YX88iLJ3IhnldwrKxWM',
    appId: '1:596238938882:ios:YOUR_IOS_APP_ID', // TODO: Add macOS app if needed
    messagingSenderId: '596238938882',
    projectId: 'storehsk-94540',
    storageBucket: 'storehsk-94540.firebasestorage.app',
    iosBundleId: 'com.example.storehsk',
  );
}
